# Generated by Django 3.1.1 on 2021-04-14 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('pay', models.CharField(max_length=30)),
                ('benefits', models.TextField()),
                ('location', models.CharField(max_length=50)),
                ('notes', models.TextField()),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
