# Generated by Django 3.1.1 on 2021-04-14 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='company_name',
            new_name='company',
        ),
    ]
