# Generated by Django 3.1.1 on 2021-04-29 02:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210416_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='date_applied',
            field=models.DateField(default=datetime.date(2021, 4, 29)),
        ),
    ]
